"""Create initial tables

Revision ID: 6ccd1d7e2917
Revises: 
Create Date: 2023-09-28 16:41:21.338914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccd1d7e2917'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synchronization_dates',
    sa.Column('insertion_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_synchronization_dates'))
    )
    op.create_table('trainings',
    sa.Column('insertion_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('durationMinutes', sa.Integer(), nullable=False),
    sa.Column('performances', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainings'))
    )
    op.create_table('workouts',
    sa.Column('insertion_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('totalRepetitions', sa.Integer(), nullable=False),
    sa.Column('maxRepetitionsInSet', sa.Integer(), nullable=False),
    sa.Column('performances', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workouts'))
    )
    op.create_table('training_timestamps',
    sa.Column('insertion_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainingId', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trainingId'], ['trainings.id'], name=op.f('fk_training_timestamps_trainingId_trainings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_timestamps'))
    )
    op.create_table('workout_timestamps',
    sa.Column('insertion_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workoutId', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workoutId'], ['workouts.id'], name=op.f('fk_workout_timestamps_workoutId_workouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_timestamps'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_timestamps')
    op.drop_table('training_timestamps')
    op.drop_table('workouts')
    op.drop_table('trainings')
    op.drop_table('synchronization_dates')
    # ### end Alembic commands ###
